#!/bin/zsh


source "${0:A:h}"/.env
source "${0:A:h}"/alias/docker
source "${0:A:h}"/alias/npm

PATH="$PATH:${0:A:h}/bin:$HOME/.composer/vendor/bin"

chmod +x "${0:A:h}"/bin/*

# shellcheck disable=SC1090
source ~/.iterm2_shell_integration.zsh

docker-toolbox completion > "${0:A:h}"/completion/docker-toolbox
source "${0:A:h}"/completion/docker-toolbox
